add a new optional param to provide production tasks to be run

diff --git a/.github/workflows/deploy-sync.yml b/.github/workflows/deploy-sync.yml
--- a/.github/workflows/deploy-sync.yml
+++ b/.github/workflows/deploy-sync.yml
@@ -68,6 +68,11 @@ on:
         type: boolean
       commands:
         default: '["skip"]'
+        description: 'An array of commands to be run agaisnt the development layer of the docker image'
+        type: string
+      production_commands:
+        default: '["skip"]'
+        description: 'An array of commands to be run agaisnt the production layer of the docker image'
         type: string
       workflow_id:
         description: 'This is an id that is used for things like artifacts, needed when being called in a matrix'
@@ -335,7 +340,7 @@ jobs:
           IMAGE_TAG_SOURCE: ${{ needs.init.outputs.GITHUB_BRANCH_LATEST_IMAGE_ID_TAG }}
           JOB_ID: ${{inputs.workflow_id}}-production
 
-  commands:
+  test-image-commands:
     needs: [init, post-build-test]
     strategy:
       matrix:
@@ -366,6 +371,50 @@ jobs:
         run: |
           docker pull ${{ needs.init.outputs.GITHUB_BRANCH_TEST_IMAGE_ID_TAG }}
           ${{ format(matrix.command, needs.init.outputs.GITHUB_BRANCH_TEST_IMAGE_ID_TAG) }}
+
+      - name: zip artifacts
+        id: zip_failures
+        if: always() && steps.run.outcome == 'failure' && needs.init.outputs.IS_DEFAULT_BRANCH_PUSH != 'true' && inputs.save_test_artifacts
+        run: |
+          if [ -n "$(find /tmp/screenshots -mindepth 1 -print -quit)" ]; then
+            zip -r screenshots.zip /tmp/screenshots
+            echo "UPLOAD_FAILURES=true" >> $GITHUB_OUTPUT
+            COMMAND_CLEANED=$(echo "${{matrix.command}}" | tr '[:space:]/\:*?"<>|' '_' )
+            echo "UPLOAD_UUID=$(uuidgen)-${COMMAND_CLEANED:0:200}" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Upload screenshots
+        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
+        if: always() && steps.zip_failures.outputs.UPLOAD_FAILURES == 'true' && needs.init.outputs.IS_DEFAULT_BRANCH_PUSH != 'true' && inputs.save_test_artifacts
+        with:
+          name: failed_images-${{steps.zip_failures.outputs.UPLOAD_UUID}}
+          path: screenshots.zip
+          retention-days: 7
+
+  production-image-commands:
+    needs: [init, post-build-production]
+    strategy:
+      matrix:
+        arch: ${{ (inputs.production_commands != '["skip"]' && needs.init.outputs.IS_SLASH_DEPLOY == 'false' &&  fromJSON(inputs.platforms)) || fromJSON('["linux/amd64"]') }}
+        command: ${{ fromJSON(inputs.production_commands) }}
+    runs-on: ${{ (matrix.arch == 'linux/amd64' && ((contains(matrix.command, 'BETTER_RUNNER') && needs.init.outputs.INTEL_RUNNER) || needs.init.outputs.INTEL_RUNNER_CHEAP)) || ((contains(matrix.command, 'BETTER_RUNNER') && needs.init.outputs.ARM_RUNNER) || needs.init.outputs.ARM_RUNNER_CHEAP) }}
+    name: ${{ format(matrix.command, '') }} (${{ matrix.arch }})
+    steps:
+      - uses: ausaccessfed/workflows/.github/actions/init@main
+        if: inputs.commands != '["skip"]' && needs.init.outputs.IS_SLASH_DEPLOY == 'false'
+        with:
+          BRANCH_NAME: ${{ needs.init.outputs.BRANCH_NAME }}
+          ROLE: ${{ secrets.ROLE }}
+          ECR_REPOSITORY: ${{ inputs.ecr_repository }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_ACTOR: ${{ github.actor }}
+
+      - name: Run
+        id: run
+        if: inputs.commands != '["skip"]' && needs.init.outputs.IS_SLASH_DEPLOY == 'false'
+        run: |
+          docker pull ${{ needs.init.outputs.GITHUB_BRANCH_LATEST_IMAGE_ID_TAG }}
+          ${{ format(matrix.command, needs.init.outputs.GITHUB_BRANCH_LATEST_IMAGE_ID_TAG) }}
 
       - name: zip artifacts
         id: zip_failures
@@ -474,7 +523,17 @@ jobs:
           SUPPRESS_FAILURE: true
 
   push-to-ecr:
-    needs: [init, commands, trivy-cve-scan, grype-cve-scan, snyk-cve-scan, hadolint, dockle-lint]
+    needs:
+      [
+        init,
+        test-image-commands,
+        trivy-cve-scan,
+        grype-cve-scan,
+        snyk-cve-scan,
+        hadolint,
+        dockle-lint,
+        production-image-commands
+      ]
     if: needs.init.outputs.SHOULD_PUSH_IMAGE_TO_ECR == 'true'
     strategy:
       matrix:
@@ -585,7 +644,8 @@ jobs:
         init,
         build-test,
         build-production,
-        commands,
+        test-image-commands,
+        production-image-commands,
         hadolint,
         dockle-lint,
         trivy-cve-scan,
@@ -616,8 +676,12 @@ jobs:
             OUTPUT="${OUTPUT}Building the Production image has failed!"
           fi
 
-          if [ "${{ needs.commands.result }}" == "failure" ]; then
-            OUTPUT="${OUTPUT}Some of the commands have failed!"
+          if [ "${{ needs.test-image-commands.result }}" == "failure" ]; then
+            OUTPUT="${OUTPUT}Some of the test-image-commands have failed!"
+          fi
+
+           if [ "${{ needs.production-image-commands.result }}" == "failure" ]; then
+            OUTPUT="${OUTPUT}Some of the production-image-commands have failed!"
           fi
 
           if [ "$OUTPUT" == "" ]; then
@@ -652,7 +716,8 @@ jobs:
         init,
         build-test,
         build-production,
-        commands,
+        test-image-commands,
+        production-image-commands,
         hadolint,
         dockle-lint,
         trivy-cve-scan,
@@ -668,7 +733,7 @@ jobs:
     steps:
       - name: check for failures
         run: |
-          STRING="${{ needs.init.result }}${{ needs.build-test.result }}${{ needs.build-production.result }}${{ needs.commands.result }}${{ needs.hadolint.result }}${{ needs.dockle-lint.result }}${{ needs.trivy-cve-scan.result }}${{ needs.grype-cve-scan.result }}${{ needs.snyk-cve-scan.result }}${{ needs.push-to-ecr.result }}${{ needs.update-production-manifests.result }}${{ needs.update-terraform-manifests.result }}"
+          STRING="${{ needs.init.result }}${{ needs.build-test.result }}${{ needs.build-production.result }}${{ needs.test-image-commands.result }}${{ needs.production-image-commands.result }}${{ needs.hadolint.result }}${{ needs.dockle-lint.result }}${{ needs.trivy-cve-scan.result }}${{ needs.grype-cve-scan.result }}${{ needs.snyk-cve-scan.result }}${{ needs.push-to-ecr.result }}${{ needs.update-production-manifests.result }}${{ needs.update-terraform-manifests.result }}"
           if [ "$(echo "$STRING" | grep "failure" || echo "")" != "" ]; then
             exit 1
           fi
